apiVersion: v1
kind: Service
metadata:
  name: reactbdarija-front-svc
  labels:
    app: reactbdarija-front
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: reactbdarija-front
    tier: frontend